apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zigbee2mqtt.fullname" . }}
  labels:
    {{- include "zigbee2mqtt.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "zigbee2mqtt.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- $configmap := lookup "v1" "ConfigMap" .Release.Namespace (printf "%s-config" (include "zigbee2mqtt.fullname" .)) }}
        {{- if $configmap }}
        configmap.resourceVersion: {{ $configmap.metadata.resourceVersion | quote }}
        {{- else }}
        configmap.revision: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "zigbee2mqtt.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "zigbee2mqtt.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.configSeed.enabled }}
      initContainers:
        - name: defaults
          image: "{{ .Values.configSeed.image.repository }}:{{ .Values.configSeed.image.tag }}"
          imagePullPolicy: {{ .Values.configSeed.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
          args:
            - |
              set -eu
              mkdir -p /app/data
              # Always copy the latest configuration from configmap
              echo "Updating configuration from configmap"
              cp /defaults/configuration.yaml /app/data/configuration.yaml
              cp /defaults/configuration.yaml /app/data/configuration.orig.yaml
          volumeMounts:
            - name: zigbee2mqtt-data
              mountPath: /app/data
            - name: zigbee2mqtt-config
              mountPath: /defaults
          {{- with .Values.configSeed.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            privileged: true
            {{- with .Values.securityContext }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if hasPrefix "/dev/" .Values.config.serial.port }}
            - name: serial
              mountPath: {{ .Values.config.serial.port }}
              readOnly: false
          {{- end }}
            - name: zigbee2mqtt-data
              mountPath: /app/data
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- if hasPrefix "/dev/" .Values.config.serial.port }}
        - name: serial
          hostPath:
            path: {{ .Values.config.serial.port }}
            type: CharDevice
        {{- end }}
        - name: zigbee2mqtt-data
          {{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
          {{- else if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "zigbee2mqtt.fullname" . }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: zigbee2mqtt-config
          configMap:
            name: {{ include "zigbee2mqtt.fullname" . }}-config
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
