apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zigbee2mqtt.fullname" . }}-config
  labels:
    {{- include "zigbee2mqtt.labels" . | nindent 4 }}
data:
  configuration.yaml: |
    {{- $cfg := .Values.config }}
    serial:
        {{ $cfg.serial | toYaml | nindent 8 }}
    mqtt:
        server: mqtt://{{ $cfg.mqtt.server }}:{{ $cfg.mqtt.port }}
        {{ with $cfg.mqtt.client_id }}client_id: {{ . | toYaml }}{{ end }}
    frontend:
        enabled: true
        package: zigbee2mqtt-windfront
        port: 8080
        host: 0.0.0.0
        url: {{ $cfg.frontend.internal_url }}
    homeassistant:
        enabled: true
    advanced:
        log_level: debug
        {{ with $cfg.pan_id }}pan_id: {{ . }}{{- end }}
        {{ with $cfg.ext_pan_id }}ext_pan_id: {{ include "hex.toBytes" (dict "value" . "requiredLength" 8) }}{{ end }}
        {{ with $cfg.network_key }}network_key: {{ include "hex.toBytes" (dict "value" . "requiredLength" 16) }}{{- end }}
        {{ with $cfg.channel }}channel: {{ . | toYaml }}{{- end }}
