apiVersion: v1
kind: Service
metadata:
  name: zstackmulator
  labels:
    app: zstackmulator
    app.kubernetes.io/name: zstackmulator
    app.kubernetes.io/component: adapter
spec:
  selector:
    app: zstackmulator
  ports:
    - name: zstack
      port: 6638
      targetPort: 6638
      protocol: TCP
  type: ClusterIP
