apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homeassistant.fullname" . }}-pvc
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  {{- with .Values.config.volume.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.config.volume.size }}
