apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto.fullname" . }}-config
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
data:
  mosquitto.conf: |
    {{- $cfg := .Values.config }}
    persistence {{ ternary "true" "false" $cfg.persistence }}
    persistence_location {{ $cfg.persistenceLocation }}
    allow_anonymous {{ ternary "true" "false" $cfg.allowAnonymous }}
    log_dest stdout
    {{- if and .Values.auth.enabled (or .Values.auth.existingSecret (gt (len .Values.auth.users) 0)) }}
    password_file /mosquitto/secrets/{{ .Values.auth.passwordFileName }}
    {{- end }}
    listener {{ $cfg.listener.plain.port }}{{- if $cfg.listener.plain.bindAddress }} {{ $cfg.listener.plain.bindAddress }}{{- end }}
    {{- range $line := $cfg.extraEntries }}
    {{ $line }}
    {{- end }}
