{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
{{- if not (gt (len .Values.auth.users) 0) }}
  {{- fail "auth.enabled is true but neither auth.existingSecret nor auth.users are defined" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mosquitto.fullname" . }}-auth
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.passwordFileName }}: {{ printf "%s\n" (join "\n" .Values.auth.users) | b64enc }}
{{- end }}
