apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homeassistant.fullname" . }}-configuration
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
data:
  automations.yaml: |-

  configuration.yaml: |
    {{- $cfg := .Values.config }}
    default_config:
    frontend:
      themes: !include_dir_merge_named themes
    automation: !include automations.yaml
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/8
    # Home Assistant configuration.yaml
    homeassistant:
      name: {{ $cfg.name | default "Home" }}
      latitude: {{ $cfg.latitude | default 0.0 }}
      longitude: {{ $cfg.longitude | default 0.0 }}
      elevation: {{ $cfg.elevation | default 0 }}
      unit_system: {{ $cfg.unit_system | default "metric" }}
      currency: {{ $cfg.currency | default "USD" }}
      country: {{ $cfg.country | default "US" }}
      external_url: {{ $cfg.external_url | default "http://example.com" }}
      internal_url: {{ $cfg.internal_url | default "http://homeassistant.local" }}
