apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homeassistant.fullname" . }}-configuration
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
data:
  automations.yaml: |-

  configuration.yaml: |
    default_config:
    frontend:
      themes: !include_dir_merge_named themes
    automation: !include automations.yaml
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/8
    # Home Assistant configuration.yaml
    homeassistant:
      name: {{ .Values.homeassistant.name | default "Home" }}
      latitude: {{ .Values.homeassistant.latitude | default 0.0 }}
      longitude: {{ .Values.homeassistant.longitude | default 0.0 }}
      elevation: {{ .Values.homeassistant.elevation | default 0 }}
      unit_system: {{ .Values.homeassistant.unit_system | default "metric" }}
      currency: {{ .Values.homeassistant.currency | default "USD" }}
      country: {{ .Values.homeassistant.country | default "US" }}
      external_url: {{ .Values.homeassistant.external_url | default "http://example.com" }}
      internal_url: {{ .Values.homeassistant.internal_url | default "http://homeassistant.local" }}
