apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homeassistant.fullname" . }}-pvc
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.homeassistant.volume.size }}
